services:
  app1:
    image: myapp
    ports:
      - "8080:8080"
    networks:
      - app-network

  app2:
    image: myapp
    ports:
      - "8081:8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg_data: